HALSERVER_VERSION = 1.0.0
OTKVM_HALSERVER_DEB = libhal-mlx-ot-kvm-$(HALSERVER_VERSION)-amd64.deb
$(OTKVM_HALSERVER_DEB)_URL = "https://raw.githubusercontent.com/oplinkoms/sonic-libmlx/main/$(OTKVM_HALSERVER_DEB)"

$(OTKVM_HALSERVER_DEB)_DEPENDS += $(LIBTHRIFT_0_14_1) $(LIBTHRIFT_0_14_1_DEV)
$(OTKVM_HALSERVER_DEB)_RDEPENDS += $(LIBTHRIFT_0_14_1)

SONIC_ONLINE_DEBS += $(OTKVM_HALSERVER_DEB)