# OT-KVM Platform modules

OTKVM_OLSV_PLATFORM_MODULE_VERSION = 1.1
export OTKVM_OLSV_PLATFORM_MODULE_VERSION

OTKVM_OLSV_PLATFORM_MODULE = sonic-platform-ot-kvm-ols-v_$(OTKVM_OLSV_PLATFORM_MODULE_VERSION)_amd64.deb
$(OTKVM_OLSV_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-ot-kvm
$(OTKVM_OLSV_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(OTKVM_HALCLIENT_DEB)
$(OTKVM_OLSV_PLATFORM_MODULE)_PLATFORM = x86_64-ot-kvm_x86_64-r0

SONIC_DPKG_DEBS += $(OTKVM_OLSV_PLATFORM_MODULE)
