# util-lib of oplink

OPLINKUTIL_VERSION = 1.0.0

OPLINKUTIL = oplinkutil_$(OPLINKUTIL_VERSION)_$(CONFIGURED_ARCH).deb
$(OPLINKUTIL)_SRC_PATH = $(PLATFORM_PATH)/util-lib
SONIC_MAKE_DEBS += $(OPLINKUTIL)

OPLINKUTIL_DEV = oplinkutil-dev_$(OPLINKUTIL_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(OPLINKUTIL),$(OPLINKUTIL_DEV)))

export OPLINKUTIL OPLINKUTIL_DEV
