# hal of oplink

OPLINKHAL_VERSION = 1.0.0

OPLINKHAL = oplinkhal_$(OPLINKHAL_VERSION)_$(CONFIGURED_ARCH).deb
$(OPLINKHAL)_SRC_PATH = $(PLATFORM_PATH)/hal
$(OPLINKHAL)_DEPENDS += $(OPLINKUTIL) $(OPLINKUTIL_DEV)
$(OPLINKHAL)_RDEPENDS += $(OPLINKUTIL)
SONIC_MAKE_DEBS += $(OPLINKHAL)

OPLINKHAL_DEV = oplinkhal-dev_$(OPLINKHAL_VERSION)_$(CONFIGURED_ARCH).deb
$(eval $(call add_derived_package,$(OPLINKHAL),$(OPLINKHAL_DEV)))

export OPLINKHAL OPLINKHAL_DEV
