# docker image for ols agent

DOCKER_OLS_STEM = docker-ols
DOCKER_OLS = $(DOCKER_OLS_STEM).gz
DOCKER_OLS_DBG = $(DOCKER_OLS_STEM)-$(DBG_IMAGE_MARK).gz

$(DOCKER_OLS)_PATH = $(DOCKERS_PATH)/docker-ols

$(DOCKER_OLS)_DEPENDS += $(OLSD) $(LIBSWSSCOMMON) $(PYTHON3_SWSSCOMMON)

$(DOCKER_OLS)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_DEPENDS)
$(DOCKER_OLS)_DBG_DEPENDS += $(OLSD_DBG) $(LIBSWSSCOMMON_DBG)

$(DOCKER_OLS)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_BULLSEYE)_DBG_IMAGE_PACKAGES)

$(DOCKER_OLS)_PYTHON_WHEELS += $(DBSYNCD_PY3)
$(DOCKER_OLS)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_BULLSEYE)

$(DOCKER_OLS)_VERSION = 1.0.0
$(DOCKER_OLS)_PACKAGE_NAME = ols
$(DOCKER_OLS)_WARM_SHUTDOWN_BEFORE = swss
$(DOCKER_OLS)_FAST_SHUTDOWN_BEFORE = swss

SONIC_DOCKER_IMAGES += $(DOCKER_OLS)
SONIC_INSTALL_DOCKER_IMAGES += $(DOCKER_OLS)

SONIC_DOCKER_DBG_IMAGES += $(DOCKER_OLS_DBG)
SONIC_INSTALL_DOCKER_DBG_IMAGES += $(DOCKER_OLS_DBG)

$(DOCKER_OLS)_CONTAINER_NAME = ols
$(DOCKER_OLS)_RUN_OPT += -t --cap-add=NET_ADMIN
$(DOCKER_OLS)_RUN_OPT += -v /etc/sonic:/etc/sonic:ro
$(DOCKER_OLS)_RUN_OPT += -v /etc/timezone:/etc/timezone:ro 

$(DOCKER_OLS)_BASE_IMAGE_FILES += olsctl:/usr/bin/syslogalm
$(DOCKER_OLS)_BASE_IMAGE_FILES += olscli:/usr/bin/operationd
$(DOCKER_OLS)_BASE_IMAGE_FILES += olscli:/usr/bin/autoctrld
$(DOCKER_OLS)_FILES += $(SUPERVISOR_PROC_EXIT_LISTENER_SCRIPT)

SONIC_BULLSEYE_DOCKERS += $(DOCKER_OLS)
SONIC_BULLSEYE_DBG_DOCKERS += $(DOCKER_OLS_DBG)
